# Generated by Django 2.0 on 2017-12-26 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Job_lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Job')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Lang')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('death', models.DateField()),
                ('gender', models.IntegerField(choices=[(1, 'Female'), (2, 'Male')])),
                ('place_of_birthday', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('homepage', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Person_lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField()),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Lang')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='langs',
            field=models.ManyToManyField(through='person.Person_lang', to='common.Lang'),
        ),
        migrations.AddField(
            model_name='job',
            name='langs',
            field=models.ManyToManyField(through='person.Job_lang', to='common.Lang'),
        ),
    ]
