# Generated by Django 2.0 on 2017-12-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20171226_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='langs',
            field=models.ManyToManyField(blank=True, through='person.Person_lang', to='common.Lang'),
        ),
    ]
