# Generated by Django 2.0 on 2017-12-26 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id_tmdb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='average',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='backdrop',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, null=True, through='movie.Cast', to='person.Person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='movie.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='langs',
            field=models.ManyToManyField(blank=True, null=True, through='movie.Movie_lang', to='common.Lang'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ratings',
            field=models.ManyToManyField(blank=True, null=True, through='movie.Rating', to='movie.Source'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie_lang',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie_lang',
            name='poster',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie_lang',
            name='trailer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.Movie'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='sourceid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
