# Generated by Django 2.0 on 2017-12-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20171226_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, through='movie.Cast', to='person.Person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='movie.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='langs',
            field=models.ManyToManyField(blank=True, through='movie.Movie_lang', to='common.Lang'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ratings',
            field=models.ManyToManyField(blank=True, through='movie.Rating', to='movie.Source'),
        ),
    ]
